Upgrade dependecnices
zetaapps/zeta pull request #10
Opened 2016-12-28 08:26 UTC by manjunathc23

Upgrade dagger, play services, support libs and typo in the `dependencies.gradle`

2016-12-28 15:05 UTC, manijshrestha requested changes
Looks good!

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        mockitoVersion                    : 'mockito-core:1.10.19',
any reason to move `mockito-core` part here? Let's move it back in the dependencies block?

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        aptPlugin         : "com.neenbedankt.gradle.plugins:android-apt:1.8",
🤔 , this was removed in favor of build in `annotationProcessor`. any reason to bringing it back?

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        appIndexing                : "com.google.firebase:firebase-appindexing:$versions.playServicesVersion",
👍

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
>          targetSdk                         : 23,
Lets bump this and compileSdk to 25?

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        buildTools                        : "25.0.1",
lets even go up to `25.0.2`?

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        networkSamplerVersion             : "connectionclass:1.0.1",
lets move the artifactId to dependencies block?

2016-12-28 15:05 UTC, manijshrestha commented on dependencies.gradle
> +        orgDotJson                 : "org.json:json:20140107",
🤔 would we need this? If we do, shall we use the latest version? `20160810`?

2016-12-28 16:45 UTC, manjunathc23 commented on dependencies.gradle
>          targetSdk                         : 23,
Sure 👍

2016-12-28 16:46 UTC, manjunathc23 commented on dependencies.gradle
> +        buildTools                        : "25.0.1",
Yep 👍

2016-12-28 16:46 UTC, manjunathc23 commented on dependencies.gradle
> +        networkSamplerVersion             : "connectionclass:1.0.1",
For some reason it wont compile if I do so. Can you check at your end too?

2016-12-28 16:47 UTC, manjunathc23 commented on dependencies.gradle
> +        mockitoVersion                    : 'mockito-core:1.10.19',
compilation reason. Can you check from your end too?

2016-12-28 16:47 UTC, manjunathc23 commented on dependencies.gradle
> +        aptPlugin         : "com.neenbedankt.gradle.plugins:android-apt:1.8",
May be butterknife needs it. Will confirm you.

2016-12-28 16:48 UTC, manjunathc23 commented on dependencies.gradle
> +        orgDotJson                 : "org.json:json:20140107",
We can remove this. Not currently in use.

2016-12-29 04:45 UTC, manjunathc23 commented
@manijshrestha  ^ take a look now. New commits are up.

2016-12-29 18:30 UTC, manijshrestha approved these changes
💯

2016-12-29 18:50 UTC, manijshrestha commented
Looks good. Lets move the artifact-id down to the dependencies block and it all looks good.

2017-02-23 06:04 UTC, manjunathc23 commented
Closing this PR as i'll raise the new one. Thanks @manijshrestha

2017-02-23 06:04 UTC, closed without merging